### ISSUE TITLE
Footer overlaps content

### ISSUE THREAD

**Issue by vinhtq** [bolan9999/react-native-spring-scrollview#14]
If the last item has long text then the Footer will overlap the content.

<img width="602" alt="screen shot 2019-02-14 at 11 04 59 am" src="https://user-images.githubusercontent.com/3962520/52762073-96f61900-3048-11e9-9cec-468761c73116.png">

**Comment by bolan9999** [comment]
Sorry, I am on Chinese new year holiday last days. 

This problem may occur when you use a `bottoming` Loading style.
You must set a backgroundColor in `contentStyle` to cover it.

**Comment by vinhtq** [comment]
Thank you for your response!

The loading style I use is `stickyContent` not `bottoming` and the background for `contentStyle` is already set

I paid attention that this happens when SpringScrollView has about 200 items and the last item has long text. This leads to calculating the position of the footer has some wrong value

**Comment by bolan9999** [comment]
Why you use SpringScrollView with so many items? SpringScrollView simply renders all its react child components at once. Performance issue may occur in this scene.

If you are sure, give me your code and your datasource and let me debug it.

**Comment by bolan9999** [comment]
I will fix the `TouchableOpacity` problem and release [`react-native-largelist` Version 3](https://github.com/bolan9999/react-native-largelist)

**Comment by vinhtq** [comment]
The problem that I cannot use large-list because it conflicts with `react-navigation` library.

`gestureHandlerRootHOC` cannot be used with `react-navigation` library

**Comment by bolan9999** [comment]
Version 3 will not use `react-native-gesture-handler` and `gestureHandlerRootHOC`

**Comment by vinhtq** [comment]
That would be awesome! Meanwhile I need to resolve this issue before my project ends.

Will really appreciate if you can help

**Comment by bolan9999** [comment]
give me your code and your datasource and let me debug it.

**Comment by vinhtq** [comment]
Here is the example. I hope it can help you
https://gist.github.com/vinhtq/15c8ebcf89d2aac15092d5e747409146

**Comment by bolan9999** [comment]
Try this:
```
<SpringScrollView
    style={{flexGrow: 1, flexShrink: 1, overflow: 'scroll'}}
    //other props
    >
        ...
</SpringScrollView>
```

**Comment by vinhtq** [comment]
Still not working. 

Checked on emulator iPhone 6, ios version 12.1

<img width="384" alt="screen shot 2019-02-14 at 2 39 07 pm" src="https://user-images.githubusercontent.com/3962520/52770673-4e4d5880-3066-11e9-937a-1180953693aa.png">

**Comment by bolan9999** [comment]
It works on your example. I have tested it.

**Comment by bolan9999** [comment]
![simulator screen shot - iphone 8 - 2019-02-14 at 15 45 14](https://user-images.githubusercontent.com/14797923/52770970-8f963600-306f-11e9-8362-9d85b3db2618.png)

**Comment by vinhtq** [comment]
Can you check it on emulator iphone 6
![screen shot 2019-02-14 at 2 44 51 pm](https://user-images.githubusercontent.com/3962520/52770963-29a5b080-3067-11e9-8680-c5af9e1bc362.png)

**Comment by bolan9999** [comment]
![2019-02-14 3 49 41](https://user-images.githubusercontent.com/14797923/52771168-2c58d380-3070-11e9-970d-4420b90864bc.png)

Yes, it also works well. Maybe it is the react-native version problem, mine is 0.55.4

**Comment by vinhtq** [comment]
Yes look like the react native version. I am using version 0.57.4

**Comment by bolan9999** [comment]
Have you tried 0.55.4, how about it ?

**Comment by vinhtq** [comment]
I got some error regarding to downgrade the react native version. Need a little bit time to resolve this

**Comment by vinhtq** [comment]
Sorry downgrade from 0.57 to .055 requires a lot of changes in the configuration. Will pm you soon

**Comment by vinhtq** [comment]
Is there any other way to fix this issue beside downgrade react-native version?

**Comment by bolan9999** [comment]
I have upgrade my react-native version to 0.57.4, and there is no problem!

**Comment by bolan9999** [comment]
![2019-02-14 5 03 05](https://user-images.githubusercontent.com/14797923/52775363-7b0b6b00-307a-11e9-9aa7-10321993d3e4.png)
![2019-02-14 5 03 18](https://user-images.githubusercontent.com/14797923/52775364-7b0b6b00-307a-11e9-8353-05b0290c5e2e.png)

**Comment by vinhtq** [comment]
Did you reset the node module cache after installing new version of react-native?
`npm start --reset-cache`

**Comment by bolan9999** [comment]
Sure, I got a lot issues if I forgot this step.

**Comment by vinhtq** [comment]
So weird, I reset my emulator. Even init a new project but still got the issue

https://www.dropbox.com/s/owbzq34cgii4xzw/demo.7z?dl=0
Can you download this and try?

**Comment by bolan9999** [comment]
I have tried, and found out the bug. We use two different version. I use the master branch. And you use the 2.0.2. I will fix it soon.

**Comment by bolan9999** [comment]
I have released version 2.0.3 on npm. Try to update it, remember to clear watchman cache and npm cache.Then try it.
Additionally, the `TouchableOpacity` event firing issue has been fixed ,too.

**Comment by vinhtq** [comment]
Thank you for you time! But we have another issue. 
In version 2.0.2, when we add style: `paddingBottom: 50` SpringScrollView can receive this. 
![Uploading Screen Shot 2019-02-15 at 9.35.41 AM.png…](version 2.0.2)

But in version 2.0.3, SpringScrollView ignore this style.

**Comment by bolan9999** [comment]
Use this style on `contentStyle`, not `style` please.

**Comment by vinhtq** [comment]
Ok. Just remind because in previous version it works!

Thank you!

**Comment by bolan9999** [comment]
OK, I will close this issue!
