### ISSUE TITLE
IOS 当列表数量不满一屏幕时，无法进行刷新与上拉加载

### ISSUE THREAD

**Issue by Natuka** [bolan9999/react-native-spring-scrollview#16]
![image](https://user-images.githubusercontent.com/9472604/52923561-61f90780-3363-11e9-9ad4-3e5ad9ccee28.png)
无法进行下拉刷新与上拉加载，然后下方显示好像也有点问题
Android版没有该问题。

**Comment by Natuka** [comment]
版本是最新版本 2.0.3

**Comment by Natuka** [comment]
目前通过传入 contentStyle={{height: '110%'}}
可解决上拉加载的问题，，，

**Comment by Natuka** [comment]
allLoaded IOS 下不生效

**Comment by bolan9999** [comment]
contentStyle={{minHeight:'100%'}} 即可，下个版本考虑加入这个默认样式。

我刚测试了，allLoaded 在iOS下没有问题

**Comment by bolan9999** [comment]
I have published v2.0.4 to fix this issue.
