### ISSUE TITLE
[Android] Can not rebound correctly only on Android Emulator.

### ISSUE THREAD

**Issue by bolan9999** [bolan9999/react-native-spring-scrollview#2]
Can not rebound correctly only on Android Emulator. But correctly on Android really devices.

**Comment by z5614036** [comment]
大佬半年多了！！largelist那个 pollsize超过6个导致加载缓慢的现状没有改善啊！上班不忙，偷偷搞搞啊

**Comment by bolan9999** [comment]
那个问题需要重构，现在准备用这个库来重构。有空帮忙测试一下呗

**Comment by z5614036** [comment]
此库，我测试了一下，scorllview里面只有元素有flex:1就报错，我引入react-native-swiper直接报错

**Comment by bolan9999** [comment]
你pull gitub上的master最新的来试， 我已经添加了4个常用的测试用例场景

**Comment by bolan9999** [comment]
V2版本已解决已解决
