### ISSUE TITLE
如何使用pod进行安装？

### ISSUE THREAD

**Issue by jamessawyer** [bolan9999/react-native-spring-scrollview#20]
尝试使用pod进行安装，安装失败，提示没有版本
对应的pod
```
 pod 'RNSpringScrollView', :podspec => '../node_modules/react-native-spring-scrollview/ios'
```
想请问一下支持pod安装吗？
如果不支持，是否能补充一下手动安装的过程。
感谢

**Comment by jamessawyer** [comment]
另外在使用react-native-largelist-v2中，我没有link这个库，好像也没有报错。现在准备尝试使用 react-native-largelist-v3, 想体验一下，新版本是否在性能比v2版本提升很多 😊

**Comment by bolan9999** [comment]
pod我搞了半天，编译没通过，找不到RCTScrollViewManager文件，估计是上传pod的人没有公开这个文件。但是React源代码项目是公开了的。

**Comment by jamessawyer** [comment]
哦哦 我刚创建了一个新项目中,没有使用pod管理
  1. 将 **`RNSpringScrollView.xcodeproj`** 添加到 **`Libraries`** 中
  2. 在 **`项目设置 ==> TARGETS ==> BuildPhases ==> Link Binary With Libraries`** 添加 **`libRNSpringScrollView.a`**文件
这个集成是ok的。

但是现在项目是集成到已经存在的原生项目上的，使用pod管理，项目中不存在 **`Libraries`**文件夹
不知道这样描述清不清楚，想请问一下 这种情况该怎么手动的集成react-native-spring-scrollview 呢？

**Comment by bolan9999** [comment]
我大概知道什么情况了，那个podspec不需要上传，只需要github上文件齐全就行了，估计是pod进行了额外设置。我已经改好了，准备和下一个版本一起发，下一个版本支持TypeScript

**Comment by bolan9999** [comment]
其实你自己也可以改那个podspec文件

**Comment by jamessawyer** [comment]
好的 期待ts版本。podspec要改哪些地方呢？能不能指点一下 🤣

**Comment by ATShiTou** [comment]
最新版2.0.10已发布，支持TS，pod文件已更新

**Comment by jamessawyer** [comment]
好的 非常感谢！

**Comment by jamessawyer** [comment]
对旧版本进行升级， 旧版本信息：
  - react-native-spring-scrollview: 0.0.24
  -react-native-largelist-v2: 2.1.1
旧版本程序正常，旧版本中没有对react-native-spring-scrollview进行link操作

升级后
新版本版本信息：
react-native-spring-scrollview: 2.0.16
react-native-largelist-v3: 3.0.10
使用pod link react-native-spring-scrollview：
```
pod 'RNSpringScrollView', :podspec => '../node_modules/react-native-spring-scrollview/ios'
```
最新版本和使用react-native-largelist-v3一起报错,部分代码：
```
import { LargeList } from 'react-native-largelist-v3';

// ...
<LargeList
  style={styles.list}
  data={this.state.data}
  heightForSection={() => 44}
  renderSection={this._renderSection}
  heightForIndexPath={() => 40}
  ref={list => {this.list = list}}
/>
```
报错信息：
 **`requireNativeComponent: "SpringScrollContentView" was not found in the UIManager. getNativeComponentAttributes: getNativeComponentAttributes.js:29:4`**

**Comment by bolan9999** [comment]
分明是你没连接，连接了肯定不会报找不到SpringScrollView的。 还有一种可能就是你没开-ObjC编译选项，现在绝大多数模板都开了这个选项的

**Comment by bolan9999** [comment]
你这个是缺文件吧？SpringScrollView都有，contentview没有？

**Comment by bolan9999** [comment]
pod工程下面有这个文件吗？STSpringScrollContentViewManager.m

**Comment by jamessawyer** [comment]
没有这个文件，我项目里面一般pod成功的都会在 **Development Pods** 下面生成对应的文件夹，比如react-native-svg 会生成 **RNSVG** 目录，现在pod完 RNSpringScrollView， 并没有生成对应的文件夹， -Objc 编译选项是开启的。

**Comment by ATShiTou** [comment]
那就是文件都没下载成功 ？

**Comment by ATShiTou** [comment]
这几个文件都必须要有：

<img width="456" alt="屏幕快照 2019-03-15 上午11 58 00" src="https://user-images.githubusercontent.com/38748693/54409504-a3d65d00-4719-11e9-8492-981f026fa1f6.png">

**Comment by ATShiTou** [comment]
你接了这么多天了都没有接入成功吗，实在不行从github拷贝到你的工程都是可以的

**Comment by jamessawyer** [comment]
pod显示的安装成功了， 但是没有文件。这几天有别的事情 就先把升级的事情放下来了 现在空闲了又在搞这个 哈哈,  好的，我自己再研究研究，谢大佬了

**Comment by Mr-jiangzhiguo** [comment]
我也遇到这个错误了，楼主是怎么解决的，分享一下

**Comment by Mr-jiangzhiguo** [comment]
![屏幕快照 2019-05-14 15 06 07](https://user-images.githubusercontent.com/22312092/57677646-e523b400-7659-11e9-85b2-792273a22120.png)
我的也是pod 显示RNSpringScrollView 安装成功了，但是pod工程下没有文件，报的错也是这个`requireNativeComponent: "SpringScrollContentView" was not found in the UIManager.`
