### ISSUE TITLE
ios不显示刷新的头部和上拉的底部问题

### ISSUE THREAD

**Issue by JackGZY** [bolan9999/react-native-spring-scrollview#21]
` <SpringScrollView
                    refreshHeader={ChineseWithLastDateHeader}
                    contentStyle={{minHeight: '100%'}}
                    loadingFooter={ChineseWithLastDateFooter}
                    allLoaded={true}
                    onLoading={() => {
                    }}
                    onRefresh={() => {
                    }}>
                    <FlatList
                        data={this.state.data}
                        style={{flex: 1}}
                        ItemSeparatorComponent={() => {
                            return <View style={{height: 3}}></View>
                        }}
                        keyExtractor={(item, index) => index.toString()}
                        renderItem={this._renderItem}
                    />
                </SpringScrollView>`

    "react-native": "0.57.6",
    "react-native-spring-scrollview": "^2.0.17",

![E28A07DC80965871DD37679CB7CEF0DB](https://user-images.githubusercontent.com/19221577/54985916-ae7fd480-4fec-11e9-964d-512ca719a618.png)
![F67C33444BD1257E7D0534E4E7062A40](https://user-images.githubusercontent.com/19221577/54985919-b0e22e80-4fec-11e9-9b1a-53cd6fcc5a20.png)

**Comment by bolan9999** [comment]
嵌套还有问题，你这个两层明显是事件冲突，你这个可以把 FlatList的弹性关了，不过下拉应该不能无缝地刷新。

要使用列表请直接使用Largelist

**Comment by bolan9999** [comment]
在顶部或底部重新下拉过上拉应该是可以刷新和加载的，滑动应该不能出弹性。不推荐这样做
