### ISSUE TITLE
无法使用，报错

### ISSUE THREAD

**Issue by haofeng123** [bolan9999/react-native-spring-scrollview#23]
我在用LargeList 的时候想调用loadingFooter={ChineseWithLastDateFooter}的时候

报错

Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `lottie-react-native` from `/Users/a/Desktop/nwhh_v2/node_modules/react-native-spring-scrollview/Customize/CommonLottieHeader.js`: Module `lottie-react-native` does not exist in the Haste module map

**Comment by haofeng123** [comment]
已经 react-native link react-native-spring-scrollview了的

**Comment by ATShiTou** [comment]
有三种解决方案：
1. 你没有用`lottie-react-native`就这样导入，临时解决吧：
```
import {ChineseWithLastDateFooter} from "react-native-spring-scrollview/Customize/ChineseWithLastDateFooter"
```
2. 你也可以安装`lottie-react-native`三方库
3. 把`react-native-spring-scrollview/Customize/index.js`里面这两段代码注释掉也可以：
```
//export * from "./CommonLottieHeader";
//export * from "./CommonLottieFooter";
```

下个版本我把`CommonLottieHeader, CommonLottieFooter `移到Example里面去,不应该放在Customize里面

**Comment by haofeng123** [comment]
安装了lottie-react-native  解决了，谢谢
