### ISSUE TITLE
Forking and cloning this repo - ends with a SpringScrollViewExample installed

### ISSUE THREAD

**Issue by efratyo** [bolan9999/react-native-spring-scrollview#25]
Hi,
Well this may sound a bit stupid, but I'm bumping my head into it.
I've forked this repo and cloned it for a small change I've needed to make.
But when I'm npm installing it - I get the 'SpringScrollViewExample' installed (According to the package.json) instead of the 'react-native-spring-scrollview' (which is inside the 'src' folder)

I didn't see any scripts that points to the right folder while installing this repo.

Any help would be appreciated.
Thanks :)

**Comment by bolan9999** [comment]
You should publish the src diectory, not the root.

**Comment by efratyo** [comment]
I got it working, many thanks!
