### ISSUE TITLE
[Question] How can we link this library to another library ?

### ISSUE THREAD

**Issue by srikanthsunkari** [bolan9999/react-native-spring-scrollview#27]
**Environment Info:
Dev OS : windows
Target OS: Android
react-native version: ^0.58.6,
react-native-spring-scrollview: ^2.0.20**

Hi @bolan9999, please help me to integrate this library to my app library. I am trying to add this library to my library which is created by using react-native-create-library command.

 I tried to link using `react-native link react-native-spring-scrollview` command and manually, but failing to do it so. I found a [question]: [https://stackoverflow.com/questions/54219544/using-react-native-library-inside-another-react-native-library](url) saying It is not possible to add/link a library to another library. Is there any manual way to do this or not possible?

Trying to add the `react-native-spring-scrollview: ^2.0.20` library to my library `react-native-demolibrary`, which is a library created using react-native-create-library command, since it is a library there were no settings.gradle file. So created and tried to link manually library to react-native-somelibrary.

> `settings.gradle`

```
include ':react-native-spring-scrollview'
project(':react-native-spring-scrollview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-spring-scrollview/android')
```

> `build.gradle`

`implementation project(':react-native-spring-scrollview')`

below error has shown up,

> GRADLE CONSOLE ERROR

```
org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Build file 'E:\Workspace\DemoApp\node_modules\react-native-demolibrary\android\build.gradle' line: 37
A problem occurred evaluating project ':react-native-library'.
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:139)
    at org.gradle.initialization.DefaultGradleLauncher.getConfiguredBuild(DefaultGradleLauncher.java:104)
    at .....more
```

> ERROR:

`Project with path ':react-native-spring-scrollview' could not be found in project ':react-native-demolibrary'.`

Thank you for the help in advance.

**Comment by ATShiTou** [comment]
Sorry for late response. I'm not sure whether I can explain it to you in English.

A question: Why do you use `react-native-spring-scrollview` on Native? 

You should understand that react native packages just for react-native. The answer from the stackoverflow you provide has explained. You should make `react-native-spring-scrollview` as your library's dependencies. Anyone who want to use your library will install `react-native-spring-scrollview` automatically when installing your library. And you must ask them to link `react-native-spring-scrollview` manually.

**Comment by ATShiTou** [comment]
[`react-native-largelist`](https://github.com/bolan9999/react-native-largelist/tree/master/src) depends on this library. You can check it out.

Precautions:
The src folder is the `react-native-largelist` and the root folder is the demo for `react-native-largelist`
