### ISSUE TITLE
pod 安装，报错：“SpringScrollContentView” was not found

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [bolan9999/react-native-spring-scrollview#32]
pod 显示RNSpringScrollView 安装成功了：
![3E989710-C123-4DDE-83A6-E00DE36908E6](https://user-images.githubusercontent.com/22312092/57695543-19f73180-7681-11e9-8bc7-523741adebc1.png)

但是pod工程（Development Pods目录）下没有对应文件：
![屏幕快照 2019-05-14 15 06 07](https://user-images.githubusercontent.com/22312092/57677646-e523b400-7659-11e9-85b2-792273a22120.png)
然后页面报的错是`requireNativeComponent: "SpringScrollContentView" was not found in the UIManager.`

@bolan9999 @ATShiTou 

大佬，这个问题怎么解决？？？

**Comment by ATShiTou** [comment]
我没用pod安装，没时间去测试，我合并了其他人的podspec文件，你有空的话可以看看podspec文件哪里有问题。

**Comment by Mr-jiangzhiguo** [comment]
是不是应该是 s===>spec啊：
```
require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |spec|
  spec.name         = "RNLanguages"
  spec.summary      = "React Native properties and methods related to the language of the device"
  spec.version      = package['version']

  spec.authors      = { "Mathieu Acthernoene" => "zoontek@gmail.com" }
  spec.homepage     = "https://github.com/react-community/react-native-languages"
  spec.license      = "MIT"
  spec.platform     = :ios, "9.0"

  spec.source       = { :git => "https://github.com/react-community/react-native-languages.git" }
  spec.source_files = "ios/**/*.{h,m}"

  spec.dependency   "React"
end
```

**Comment by ATShiTou** [comment]
那只是个变量吧，叫什么都无所谓。你主要检查source_files，是不是路径不对。

**Comment by Mr-jiangzhiguo** [comment]
路径少了RN俩字符

**Comment by ATShiTou** [comment]
你可以把你本地nodemodules/react-native-spring-scrollview/ios/RNSpringScrollView.podspec里面的那个文件修改了，再pod install，如果成功了。然后可以把文件内容发我

**Comment by Mr-jiangzhiguo** [comment]
![BA10FCF0-3973-4A6C-A8E3-6B020FE23393](https://user-images.githubusercontent.com/22312092/57697412-b6233780-7685-11e9-8353-4f807942a7e0.png)
我修改试试

**Comment by ATShiTou** [comment]
github上面文件夹没有RN两个字，你是不是用了老版本
https://github.com/bolan9999/react-native-spring-scrollview/tree/master/src/ios

**Comment by Mr-jiangzhiguo** [comment]
我前两天才刚用的，可能缓存了，我重新删除package-lock后npm i 再试试

**Comment by ATShiTou** [comment]
你可以直接打开package.json，看看版本多少就知道对不对了。

**Comment by Mr-jiangzhiguo** [comment]
版本是 最新"react-native-spring-scrollview": "^2.0.22",

但是node_modules下的目录是老的：
![Uploading 3B4B70A8-A836-48FF-80DA-D0270B71CF49.png…]()

**Comment by Mr-jiangzhiguo** [comment]
用了最新版，我看source_files路径也对了，pod安装后，显示安装成功，但pod没有生成对应文件，仍然有这个错

**Comment by Mr-jiangzhiguo** [comment]
我整个工程重新来试试

**Comment by Mr-jiangzhiguo** [comment]
哎，还是不行，

**Comment by Mr-jiangzhiguo** [comment]
@ATShiTou 
可以了

`pod 'RNSpringScrollView', :podspec => '../node_modules/react-native-spring-scrollview/ios/RNSpringScrollView.podspec'`
换成
`pod 'RNSpringScrollView', :path => '../node_modules/react-native-spring-scrollview/ios'`

就有了对应的文件了，然后就成功了

**Comment by ATShiTou** [comment]
已添加

**Comment by eleallegue** [comment]
Hi there, 
I have a similar problem. I am using the v3 of the largelist library and therefore I have to install this library too as said in **Version requirement** in [https://bolan9999.github.io/react-native-largelist/#/en/V3/GettingStart](url).

My problem is that I am using Expo and React and I get the following problem:

Error calling RCTEventEmitter.receiveTouches
Exception calling object as function: requireNativeComponent: "SprringScrollView" was not found in the UIManager: (<unknown file>:3029)


I have the following libraries and versions installed in my app:
```
"dependencies":` {
    "@expo/samples": "2.1.1",
    "braces": "^2.3.2",
    "expo": "^32.0.6",
    "expo-app-auth": "^3.0.0",
    "firebase": "^5.8.5",
    "react": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-elements": "^1.1.0",
    "react-native-gifted-chat": "^0.7.3",
    **"react-native-largelist-v3": "^3.0.14",**
    "react-native-phone-call": "^1.0.9",
    **"react-native-spring-scrollview": "^2.0.22",**
    "react-navigation": "^3.0.9"
  },
```

and the code I am executing is this one (the one you provide as an example):
```
  _sectionCount = 10;
  _rowCount = 10;

  render() {
    const data = [];
    for (let section = 0; section < this._sectionCount; ++section) {
      const sContent = { items: [] };
      for (let row = 0; row < this._rowCount; ++row) {
        sContent.items.push(row);
      }
      data.push(sContent);
    }
    return (
      <LargeList
        style={styles.container}
        data={data}
        heightForSection={() => 50}
        renderSection={this._renderSection}
        heightForIndexPath={() => 50}
        renderIndexPath={this._renderIndexPath}
      />
    );
  }

  _renderSection = ({section: section}) => {
    return (
      <View style={styles.section}>
        <Text>
          Section {section}
        </Text>
      </View>
    );
  };

  _renderIndexPath = ({ section: section, row: row }) => {
    return (
      <View style={styles.row}>
        <Text>
          Section {section} Row {row}
        </Text>
        <View style={styles.line} />
      </View>
    );
  };
```

If you could solve this please and thank you (in english please because I am from Spain)

**Comment by ATShiTou** [comment]
Your native installation is not successful. Please check your native installation. https://bolan9999.github.io/react-native-largelist/#/en/V3/GettingStart?id=check-native-installation

**Comment by eleallegue** [comment]
The thing is that as I am doing it in React with standalone app, I do not have any of the documents that url mention. I do not know where to look.

If you could help me out please

**Comment by eleallegue** [comment]
**UPDATE**:

I found the library in my project but I am not sure if the instructions for a good intalation that are specified in the webpage must be ALL fulfilled or just the one I have.

I mean:
![Screenshot_1](https://user-images.githubusercontent.com/15983836/59085612-74da1c80-88ff-11e9-9f82-0322999e4af3.jpg)
For iOS I have that folder but the second point of [https://bolan9999.github.io/react-native-largelist/#/en/V3/GettingStart?id=check-native-installation](url) I cannot have it.

I also found the ```android``` folder and I wrote in the ```build.gradle``` what it was specified, but the other two optionsI cannot solve them.
![image](https://user-images.githubusercontent.com/15983836/59085826-27aa7a80-8900-11e9-8e92-2871ed3584a4.png)

**RESULT**:
I still get the same error I mentioned:
![image](https://user-images.githubusercontent.com/15983836/59085896-75bf7e00-8900-11e9-87bd-4520c0cbaa61.png)

**Comment by eleallegue** [comment]
The steps I cannot follow because I do not have the files or the path are:

ANDROID: 

![image](https://user-images.githubusercontent.com/15983836/59085989-b0291b00-8900-11e9-89e4-36160ddfb0d3.png)
I do not have a MainApplication.java inside the path of the library.

![image](https://user-images.githubusercontent.com/15983836/59086020-c3d48180-8900-11e9-9809-f44c2aab8f35.png)
I do not have a ```setting.gradle``` inside that path. I just have a ```build.gradle```.

![image](https://user-images.githubusercontent.com/15983836/59086091-f67e7a00-8900-11e9-8da7-e6c71fddb7d4.png)
I do not know how to look this one, so I am guessing I don't have it.


If anyone could help me please, thank you @bolan9999 @ATShiTou

**Comment by ATShiTou** [comment]
Sorry, it is not supported for linking other native library with Expo.  You must eject your project from ExpoKit to install other native library.

https://docs.expo.io/versions/v33.0.0/expokit/eject/
