### ISSUE TITLE
Duplicate interface definition for class 'RCTScrollContentViewManager'

### ISSUE THREAD

**Issue by yuanxun2007** [bolan9999/react-native-spring-scrollview#33]
Hello,

I have miss one issue like below, can you help to fix it?

![Screen Shot 2019-05-27 at 5 27 03 PM](https://user-images.githubusercontent.com/7565847/58410376-ac95c880-80a4-11e9-80bf-38b976b137a2.png)

Thanks,
Carl

**Comment by bolan9999** [comment]
Please leave more info. react-native, react-native-spring-scrollview version. And the step you install it.

**Comment by jhhnjhhn** [comment]
> Please leave more info. react-native, react-native-spring-scrollview version. And the step you install it.

我昨天遇到相同的问题
"react-native": "0.58.5",
"react-native-spring-scrollview": "^2.0.22",
"react-native-largelist-v3": "^3.0.14",

用 pod 方式导入：pod 'RNSpringScrollView', :path => './react/node_modules/react-native-spring-scrollview/ios'

看报错的意思是类名重复了，我搜了一下
React/Core/Views/ScrollView/目录下有一个 RCTScrollContentViewManager 类

**Comment by yuanxun2007** [comment]
> Please leave more info. react-native, react-native-spring-scrollview version. And the step you install it.

I'm using "react-native-spring-scrollview": "^2.0.22", import it just like @jhhnjhhn use pod：pod 'RNSpringScrollView', :path => './react/node_modules/react-native-spring-scrollview/ios'.
what's more, we're using swift, dynamic framework in pod.

**Comment by yuanxun2007** [comment]
> > Please leave more info. react-native, react-native-spring-scrollview version. And the step you install it.
> 
> I'm using "react-native-spring-scrollview": "^2.0.22", import it just like @jhhnjhhn use pod：pod 'RNSpringScrollView', :path => './react/node_modules/react-native-spring-scrollview/ios'.
> what's more, we're using swift, dynamic framework in pod.



> Please leave more info. react-native, react-native-spring-scrollview version. And the step you install it.

I can fix it like below, remove the RCTScrollContentViewManager definition, and import the RCTScrollContentViewManager
![Screen Shot 2019-05-28 at 11 59 56 AM](https://user-images.githubusercontent.com/7565847/58450124-29c24b80-8140-11e9-8238-a57f78f270b4.png)

**Comment by ATShiTou** [comment]
并不是重复了，是故意声明成那个样子的。 你们的重复定义了，是因为你们的项目应该把React的项目作为公共引入了（即每个编译文件都会自动插入React的引用）。


我写成这样，没有直接引用`< React/RCTScrollContentViewManager.h >`是因为某些版本， React并没有公开这个头文件。 无法引入

**Comment by ATShiTou** [comment]
你注释的那段代码，只是一个通过编译检查的声明而已，实际运行没有任何作用。

**Comment by yuanxun2007** [comment]
> 并不是重复了，是故意声明成那个样子的。 你们的重复定义了，是因为你们的项目应该把React的项目作为公共引入了（即每个编译文件都会自动插入React的头文件）。
> 
> 我写成这样，没有直接引用`< React/RCTScrollContentViewManager.h >`是因为某些版本， React并没有公开这个头文件。 无法引入

Can you help for this case? Otherwise, I have to made this library as internal library.

**Comment by ATShiTou** [comment]
Upload your demo project to github, and let me check it out and fix it.

**Comment by ATShiTou** [comment]
I do not use pod install, so i can not get your scene!

**Comment by V5zhou** [comment]
我也遇到了这个重复定义问题，和react-native库中冲突。

**Comment by kidasovmercury** [comment]
any solutions for react-native 0.61 and pod installation?

**Comment by bolan9999** [comment]
Update to the latest version V3.0.1-rc.5
