### ISSUE TITLE
滑动监听怎么配合reanimated用？

### ISSUE THREAD

**Issue by cani1see** [bolan9999/react-native-spring-scrollview#35]
https://github.com/cani1see/AnimationDemo/blob/8996661244ba41f2dc3667b00fd8fbd2c624e106/src/SVGHeader.js#L20

滑动监听的两个事件都不太对 直接用 onNativeContentOffsetExtract 得value 提示max stack exceed ，onScroll 提示我事件不对，

**Comment by ATShiTou** [comment]
你给那个例子里面不支持原生驱动吧

**Comment by cani1see** [comment]
@ATShiTou 不太会区分原生驱动的事件 我的例子你跑了吗 就想换scrollview为 spring-scrollview/largelist，这个动画还能做吗？

**Comment by ATShiTou** [comment]
你使用的Animated.Value和官方的Animated.Value不一样，我这个是官方的。如果你要使用的话，只有寻找两者的转换方法。

**Comment by ATShiTou** [comment]
我看了一下他的代码，你需要用他的的createAnimatedComponent替换我的SpringScrollVIew里面的createAnimatedComponent这个，不然应该不行。需要改一小点这个库的代码,在[这里](https://github.com/bolan9999/react-native-spring-scrollview/blob/master/src/SpringScrollView.js#L529)改

```
const SpringScrollViewNative = Animated.createAnimatedComponent(
  requireNativeComponent("SpringScrollView", SpringScrollView)
);
```

**Comment by ATShiTou** [comment]
我刚用你的项目试了，把`SpringScrollVIew.js`里面的Animated替换成`react-native-reanimated `的。
然后注释掉这个就能正常运行了，安卓iOS都没有问题。
```
 _beginIndicatorDismissAnimation() {
    // this._indicatorOpacity.setValue(1);
    // this._indicatorAnimation && this._indicatorAnimation.stop();
    // this._indicatorAnimation = Animated.timing(this._indicatorOpacity, {
    //   toValue: 0,
    //   delay: 500,
    //   duration: 500,
    //   useNativeDriver: true
    // });
    // this._indicatorAnimation.start(({ finished }) => {
    //   if (!finished) {
    //     this._indicatorOpacity.setValue(1);
    //   }
    //   this._indicatorAnimation = null;
    // });
  }
```
有个问题就是安卓上进度条不能隐藏了，这个问题应该是他的库的问题，或者是和官方的使用方法有不一样的问题。timing函数报错了。
