### ISSUE TITLE
AsyncStorage extracted from react-native core

### ISSUE THREAD

**Issue by artdza25** [bolan9999/react-native-spring-scrollview#36]
I use RN 0.59.8 and am now seeing this warning message:

Warning: Async Storage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/async-storage' instead of 'react-native'. See https://github.com/react-native-community/react-native-async-storage

**Comment by ATShiTou** [comment]
I will try to fix it recently.

**Comment by dmarkowski** [comment]
Any progress on that?

**Comment by bolan9999** [comment]
Update to the latest version V3.0.1-rc.5
