### ISSUE TITLE
RCTScrollContentViewManager 重复定义

### ISSUE THREAD

**Issue by sdutlyb** [bolan9999/react-native-spring-scrollview#38]
react/core 中有 RCTScrollContentViewManager, 你为什么自己定义这样一个类，导致安装后编译报错？

**Comment by bolan9999** [comment]
那demo为什么还运行得起来？

**Comment by ATShiTou** [comment]
可能是编译配置不同，比如默认加入react的所有头文件导入，会有编译问题。使用默认的配置是没问题的。

声明只要不在同一个.m编译文件，多次定义没有问题的。  之前专门定义这个是因为，在某些react的版本里面，RCTScrollContentViewManager 等没有直接导出。所以自己写的一个声明

**Comment by sdutlyb** [comment]
对的，以静态库编译pods正常，改成动态方式这里就会出这个问题。





------------------ 原始邮件 ------------------
发件人: ATShiTou <notifications@github.com>
发送时间: 2019年8月14日 23:04
收件人: bolan9999/react-native-spring-scrollview <react-native-spring-scrollview@noreply.github.com>
抄送: bin <386026448@qq.com>, Author <author@noreply.github.com>
主题: 回复：[bolan9999/react-native-spring-scrollview] RCTScrollContentViewManager 重复定义 (#38)




可能是编译配置不同，比如默认加入react的所有头文件导入，会有编译问题。使用默认的配置是没问题的。
 
声明只要不在同一个.m编译文件，多次定义没有问题的。  之前专门定义这个是因为，在某些react的版本里面，RCTScrollContentViewManager 等没有直接导出。所以自己写的一个声明

**Comment by bolan9999** [comment]
更新到最新版本V3.0.1-rc.5
