### ISSUE TITLE
支持0.60+autolink

### ISSUE THREAD

**Issue by vinurs** [bolan9999/react-native-spring-scrollview#39]
现在貌似还需要执行手动link，是否可以支持autolink

**Comment by minhphung210** [comment]
pod 'RNSpringScrollView', :path => '../node_modules/react-native-spring-scrollview/ios'

you can try this

**Comment by ATShiTou** [comment]
文档里早就有pod安装说明，没人看而已

**Comment by Janjiran** [comment]
> 文档里早就有pod安装说明，没人看而已

Yeah, but there is no guide on android with autolinking since > 0.60 i think.

**Comment by davidmarinangeli** [comment]
I found this problem on iOS with 0.61.2 update. 

`.../react-native-spring-scrollview/ios/SpringScrollView/STSpringScrollView.h:9:9: 'React/RCTScrollView.h' file not found`

Is there any guide with > 0.60 ?

**Comment by minhphung210** [comment]
You should unlink manual and relink by pod

**Comment by bolan9999** [comment]
更新到最新版本就是自动pod
