### ISSUE TITLE
'React/RCTScrollViewManager.h' file not found

### ISSUE THREAD

**Issue by minhphung210** [bolan9999/react-native-spring-scrollview#41]
I update react native version to 0.60.4 and build debug on simulator success but when i build on device , i have issue like that

![Screen Shot 2019-09-17 at 3 10 20 PM](https://user-images.githubusercontent.com/25664542/65023578-51daf200-d95d-11e9-8005-f513c642b6f9.png)

I need some help :(

react-native : 0.60.4
react-native-spring-scrollview: 2.0.22

**Comment by minhphung210** [comment]
close

**Comment by muyexi** [comment]
@minhphung210 Have you fixed it?

**Comment by minhphung210** [comment]
unlink manual , add this to pod file 
`pod 'RNSpringScrollView', :path => '../node_modules/react-native-spring-scrollview/ios'
`
and run pod install
i try this and success , you can try this

**Comment by muyexi** [comment]
@minhphung210 It works, thank you.

**Comment by zhangwen9229** [comment]
0.59.9, how to resolve this problem? Does anyone know about it? SOS

**Comment by zhangwen9229** [comment]
> 0.59.9, how to resolve this problem? Does anyone know about it? SOS

<img width="1276" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/5137377/130453758-b37f1612-468c-4edb-a87a-2ab34f297456.png">
I had resolve it.
