### ISSUE TITLE
tapToHideKeyboard={false} to persist keyboard doesn't work.

### ISSUE THREAD

**Issue by Genesy91** [bolan9999/react-native-spring-scrollview#44]
Even if i set tapToHideKeyboard={false}, the keyboard disappear whenever i tap outside of it.

**Comment by ATShiTou** [comment]
Maybe react native modified something about the touch system. It's too difficult to be compatible with multiple versions of react native, especially the touch system.  I'm sorry.

**Comment by bolan9999** [comment]
I have tried it works well on 0.50-0.59, but not 0.60+

**Comment by denis-tsoi-mox** [comment]
`tapToHideKeyboard` was depreciated in [d976947add72ceab2f6e5cd08ecefb2c788ed984](https://github.com/bolan9999/react-native-spring-scrollview/commit/4b3ed6c0262e4c670ef8b238f0e01ad41ca6a60d#diff-619cc2239a7eb4ef05041767e6ab0e4fb069e98ee9d2c83c2d8e1865c475e141) favour for `dragToHideKeyboard`
