### ISSUE TITLE
不支持Android X

### ISSUE THREAD

**Issue by yangbo5207** [bolan9999/react-native-spring-scrollview#47]
希望大佬能稍微修改一下引入包

![image](https://user-images.githubusercontent.com/13758605/66459324-67988e80-eaa7-11e9-92a2-0ec47f7db87c.png)

**Comment by ATShiTou** [comment]
应该是react native版本兼容性问题。

**Comment by jeffie** [comment]
Android Studio 里面Migrate to Android X 下

**Comment by yangbo5207** [comment]
@jeffie 那个东西不靠谱的

**Comment by jeffie** [comment]
> @jeffie 那个东西不靠谱的

为什么不靠谱？原理就是把你工程里的android.support包指定为androidx.support

**Comment by jaysson** [comment]
Can anyone provide a solution in English? I have the same issue.

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/71553238-c9cdb380-2a46-11ea-9bea-6cd0aa86f532.png)

**Comment by JslinSir** [comment]
replace  import androidx.annotation.NonNull;

**Comment by bolan9999** [comment]
中文 ： https://developer.android.com/jetpack/androidx/migrate?hl=zh-cn
English: https://developer.android.com/jetpack/androidx/migrate
