### ISSUE TITLE
npm上没有`2.1.0` 的版本，安装不了`2.1.0`的版本

### ISSUE THREAD

**Issue by KingAmo** [bolan9999/react-native-spring-scrollview#48]
[文档](https://bolan9999.github.io/react-native-spring-scrollview/#/zh-cn/V2/GettingStart) 中：
> react-native@0.60+：推荐使用react-native-spring-scrollview@2.1.*

执行`yarn add react-native-spring-scrollview@2.1.0`，报错如下：
```
Couldn't find any versions for "react-native-spring-scrollview" that matches "2.1.0"
? Please choose a version of "react-native-spring-scrollview" from this list: (Use arrow ke
ys)
❯ 2.0.23
  2.0.22
  2.0.21
  2.0.20
  2.0.19
  2.0.18
  2.0.17
  2.0.16
  2.0.15
  2.0.14
  2.0.13
  2.0.12
  2.0.11
  2.0.10
  2.0.9
  2.0.8
  2.0.7
  2.0.6
  2.0.5
  2.0.4
(Move up and down to reveal more choices)
```

**Comment by ATShiTou** [comment]
前两天计划支持0.60+。结果我的笔记本由于网络原因，几天没更新好系统，没有调试好。抱歉。

**Comment by ATShiTou** [comment]
2.0.23也可以运行在0.60+，只是可能要自己解决原生链接问题。

**Comment by dacsang97** [comment]
You can install `@youngtailors/react-native-spring-scrollview` (from [my fork](https://github.com/dacsang97/react-native-spring-scrollview/tree/dev)) to fix this error before @bolan9999 release version for RN 0.60+.

**Comment by rendomnet** [comment]
same here

**Comment by Coder108** [comment]
我也遇到这个问题 ，请问这个问题怎么解决呢？

**Comment by bolan9999** [comment]
已更新 3.0.1-rc.5
