### ISSUE TITLE
使用此组件 在安卓上 会导致点击事件不生效

### ISSUE THREAD

**Issue by KloveML** [bolan9999/react-native-spring-scrollview#5]
求大佬解答

**Comment by KloveML** [comment]
@bolan9999

**Comment by ATShiTou** [comment]
看看这里：

https://github.com/bolan9999/react-native-largelist/issues/171#issuecomment-411629133

和这里
https://github.com/bolan9999/react-native-largelist/issues/171#issuecomment-411719933
