### ISSUE TITLE
rn version 0.61.4

### ISSUE THREAD

**Issue by supermavericks** [bolan9999/react-native-spring-scrollview#50]
error Unable to resolve module `react-native/lib/TextInputState` from `node_modules/react-native-spring-scrollview/SpringScrollView.js`: react-native/lib/TextInputState could not be found within the project.

**Comment by dacsang97** [comment]
You can install `@youngtailors/react-native-spring-scrollview` (from [my fork](https://github.com/dacsang97/react-native-spring-scrollview/tree/dev)) to fix this error before @bolan9999 release version for RN 0.60+.

**Comment by wowtrxqn** [comment]
> @youngtailors/react-native-spring-scrollview

引用了你的版本，node_modules里面的largelist-v3/LargeList.js又要改了

**Comment by yanush** [comment]
is this going to be fixed soon?

**Comment by rendomnet** [comment]
where fix?

**Comment by bolan9999** [comment]
LargeList 3.1.0-rc.1  SpringScrollView 3.0.1-rc.5
