### ISSUE TITLE
decelerationRate

### ISSUE THREAD

**Issue by vance-liu** [bolan9999/react-native-spring-scrollview#52]
可否支持ScrollView的decelerationRate，用于决定当用户抬起手指之后，滚动视图减速停下的速度，参考[decelerationRate](https://facebook.github.io/react-native/docs/scrollview#decelerationrate)，如此可以控制滚动的速度，比较方便。

**Comment by bolan9999** [comment]
LargeList和SpringScrollView都更新到最新，iOS自己就支持，安卓可以直接修改SpringScrollView.java里的0.997f。我已经在修改了，但是没有发布。
