### ISSUE TITLE
Show more to load in footer without pulling up?

### ISSUE THREAD

**Issue by tjake** [bolan9999/react-native-spring-scrollview#55]
Hi,

I want to show more data is available to load after the last item without the user needing to start pulling up.  Is there a way todo it?  I ask because many users aren't used to pull to load more items.

**Comment by bolan9999** [comment]
Maybe you should do it via `onScroll` event.

**Comment by zhbhun** [comment]
onScroll 只返回了滚动高度，没有容器高度和容器可滚动高度

**Comment by FawadMahmood** [comment]
On android OnScroll is missing values of nativeEvent, but works well on IOS. please help.

**Comment by HrantAbrahamyan** [comment]
@bolan9999 Any update?

**Comment by bolan9999** [comment]
Try the latest version ,please.

**Comment by bolan9999** [comment]
> On android OnScroll is missing values of nativeEvent, but works well on IOS. please help.

New version works well.
