### ISSUE TITLE
Duplicate interface definition for class 'RCTScrollContentViewManager'

### ISSUE THREAD

**Issue by kidasovmercury** [bolan9999/react-native-spring-scrollview#58]
![Screenshot 2020-03-19 at 21 53 39](https://user-images.githubusercontent.com/50829747/77098722-3e076a00-6a2c-11ea-9eaa-d6484c8508ec.png)
Gettting this error while trying to build project after migration to react-native 0.61.0
Any help will be highly appreciated

**Comment by davx1992** [comment]
Same issue, have you fixed this?

**Comment by sdutlyb** [comment]
Same issue with all versions

**Comment by oferRounds** [comment]
Anyone found a solution?

**Comment by bolan9999** [comment]
There has been a major change in my life, sorry. Updated 3.0.1-rc.2
