### ISSUE TITLE
是否支持 stickyHeaderIndices

### ISSUE THREAD

**Issue by MajorMayer** [bolan9999/react-native-spring-scrollview#66]
官方的 scrollview 支持 stickyHeaderIndices 来实现固定部分元素在顶部
但是官方的安卓没有 bounce 效果

作者可以让 这个 插件也支持 stickyHeaderIndices 效果吗？

**Comment by bolan9999** [comment]
可以通过差值实现，可以运行例子查看。 在 `/Examples/ScrollToAndOnScrollExample.js` 里查找`onNativeContentOffsetExtract `.  通过这个实现！

**Comment by MajorMayer** [comment]
> ScrollToAndOnScrollExample

看了例子 还是一脸懵逼。。。。
我想要实现的是在滚动内容 中 有tab切换

当滚动时候，tab导航触碰顶部时候 固定在顶部

**Comment by bolan9999** [comment]
```
_nativeOffset = {
    y: new Animated.Value(0)
};

render(){
    return <SpringScrollView onNativeContentOffsetExtract={this._nativeOffset}>
            <Animated.View style={{transform: [{ translateY: this._nativeOffset.y }]}}>
            <YourTab />
        </Animated.View>
    </SpringScrollView>
}
```
