### ISSUE TITLE
Couldn't find any versions for "react-native-spring-scrollview" that matches "2.1.0"

### ISSUE THREAD

**Issue by rendomnet** [bolan9999/react-native-spring-scrollview#67]
Couldn't find any versions for "react-native-spring-scrollview" that matches "2.1.0"
? Please choose a version of "react-native-spring-scrollview" from this list:
  0.0.1
  2.0.23
  2.0.22
  2.0.21
  2.0.20
  2.0.19
  2.0.18
  2.0.17

**Comment by bolan9999** [comment]
try 3.0.1-rc.2 or higher
