### ISSUE TITLE
IOS上第二次下拉刷新，动画效果丢失

### ISSUE THREAD

**Issue by chj-damon** [bolan9999/react-native-spring-scrollview#69]
第一次运行正常，第二次下拉刷新的时候，发现lottie或者NormalHeader的动画效果都没了。
debug后发现offsetY在第二次的时候值没了。

**Comment by chj-damon** [comment]
安卓上面是正常的。

**Comment by bolan9999** [comment]
请给出出现你的问题的最简代码。新手可以运行Example，模仿Example写法。更新最新版本3.0.1-rc .5试试问题是否依旧？
