### ISSUE TITLE
刷新条件到达refreshing了，继续下拉有bug

### ISSUE THREAD

**Issue by 1280103995** [bolan9999/react-native-spring-scrollview#7]
下拉到了refreshing，还没刷新完成：
     1、继续下拉会改变刷新状态
     2、连续快速下拉会一直把内容往下滑出屏幕外，空白区域会一直变大（是否应该有个限制值？）
     3、在第2点上，停止下拉，等view自动回滚，内容会滑出顶部屏幕一部分，无法恢复最开始位置。

**Comment by ATShiTou** [comment]
1和2修复比较简单

**Comment by 1280103995** [comment]
问题3我是在真机上测的，问题1、2尝试修改都失败了。分享一下代码？

**Comment by ATShiTou** [comment]
这个手势处理代码是在js层的，只要你的js线程很卡的话，剧烈操作就可能出现问题3。这个必须把代码写在原生层主线程才能解决这个问题。

**Comment by ATShiTou** [comment]
问题1 你可以在自定义的Header里面过滤正在刷新的状态改变。
问题2 你可以试试将
```
  _getContentOffsetY() {
    let { dampingCoefficient, bounces } = this.props;
    if (!bounces) dampingCoefficient = 0;
    if (this._layoutChanged) {
      const bOffset = this._contentLayout.height - this._wrapperLayout.height;
      this._contentOffsetY = Animated.add(
        this._panOffsetY,
        this._animatedOffsetY
      ).interpolate({
        inputRange: [-bOffset - 1, -bOffset, 0, 1],
        outputRange: [
          -bOffset - dampingCoefficient,
          -bOffset,
          0,
          dampingCoefficient
        ]
      });
      setTimeout(() => this.props.getNativeOffset(this._contentOffsetY));
    }
  }
```
这个映射改一改(maxPullLength换成：你想设定的值/dampingCoefficient， 默认换成屏幕高度的话，就是最大只能滑动一半个屏幕)：
```
  _getContentOffsetY() {
    let { dampingCoefficient, bounces } = this.props;
    if (!bounces) dampingCoefficient = 0;
    if (this._layoutChanged) {
      const bOffset = this._contentLayout.height - this._wrapperLayout.height;
      this._contentOffsetY = Animated.add(
        this._panOffsetY,
        this._animatedOffsetY
      ).interpolate({
        inputRange: [-bOffset - 1, -bOffset, 0, maxPullLength, maxPullLength+1],
        outputRange: [
          -bOffset - dampingCoefficient,
          -bOffset,
          0,
          dampingCoefficient*maxPullLength,
          dampingCoefficient*maxPullLength
        ]
      });
      setTimeout(() => this.props.getNativeOffset(this._contentOffsetY));
    }
  }
```

**Comment by ATShiTou** [comment]
我已经在写V2版本，这次使用原生桥接的方式，可以彻底解决这个问题。 你可以clone这个V2 分支，测试一下！

**Comment by 1280103995** [comment]
其他的测了一下，没发现问题了，现在就这个类 RefreshAndLoadingExample 加载更多还有问题。
先进入这个页面，然后一直上拉加载更多，不让它回弹，拉得足够大再松开，就会有之前的问题，回不到正常位置了。

**Comment by 1280103995** [comment]
上下拉都还是有同样的问题；其他例子没有上下拉就正常，我怀疑是更新状态导致的，setState()

**Comment by bolan9999** [comment]
你怕是搞错代码了，我现在在调iOS，安卓照理说早就不能用了。你在哪个节点上 ？

**Comment by 1280103995** [comment]
是我搞错代码了

**Comment by 1280103995** [comment]
ios在公司测不了。Android现在报com.facebook.react.bridge.NoSuchKeyException: contentOffset，
然而我改了这里代码，还是不行。contentOffset.y 改成 offsetY
_onScroll = e => {
    const { offsetY,refreshStatus,loadingStatus } = e.nativeEvent;
    // console.log("refresh=====>", JSON.stringify(refreshStatus));
    this._offsetYValue = offsetY;
 ........
}

**Comment by 1280103995** [comment]
contentOffset报错这个问题解决了，但是加载更多完成后会滚动最顶部。

**Comment by 1280103995** [comment]
iOS现在还测不了，你说Android的事件会丢失，是哪些事件？

**Comment by bolan9999** [comment]
现在安卓和iOS都通过了基本测试，你可以试了

**Comment by 1280103995** [comment]
iOS xcode各种编译错误，解决不了。

Android：
1、InputExample：
         输入框焦点很难获取，点击输入框的时候scrollview滚动（scrollview是否要做个消抖处理？）
2、ScrollToAndOnScrollExample ：
         当scrollview还在滚动中调用scrollTo()，滚动会抖一下，然后滚不到指定位置
