### ISSUE TITLE
currentlyFocusedField error

### ISSUE THREAD

**Issue by abdullahIsa** [bolan9999/react-native-spring-scrollview#70]
Error details: currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput
Fix in the file SpringScrollView.js, please change currentlyFocusedField() to currentlyFocusedInput()
Thanks

**Comment by zoom2009** [comment]
same here
![image](https://user-images.githubusercontent.com/33366155/115013106-da739880-9eda-11eb-973e-5f10d19de3d2.png)

**Comment by AftabUfaq** [comment]
please change these lines and your problem will be solved. 
please make change in the file
**`node_modules\react-native-spring-scrollview\SpringScrollView.js`**
**this is on line **24** 
`import * as TextInputState from "react-native/Libraries/Components/TextInput/TextInputState";`

replace this function with this. 
this is on **500** 
```
_onTouchBegin = () => {
    if (TextInputState.currentlyFocusedInput())
      TextInputState.blurTextInput(TextInputState.currentlyFocusedInput());
    this.props.tapToHideKeyboard && Keyboard.dismiss();
    this.props.onTouchBegin && this.props.onTouchBegin();
  };
```

**Comment by bolan9999** [comment]
Try version 3.0.1-rc.2
