### ISSUE TITLE
Problem start application iOS with RN 0.64

### ISSUE THREAD

**Issue by Meelicia** [bolan9999/react-native-spring-scrollview#71]
I'm having a problem with the installed RN version (0.64) and the library version.
The problem results when the application is in building mode on XCode. Then I put screen of the error that appears on XCode.
thanks in advance to those who will answer 😇

Dev OS: Mac
Target OS: iOS
XCode: 12.5
Node: 15.12
react-native-spring-scrollview: ^2.0.23
react-native-largelist: ^3.0.15
ReactNative: 0.64.2

<img width="266" alt="121393011-3513f880-c950-11eb-941d-7a3738375bea" src="https://user-images.githubusercontent.com/66702077/122571586-2a8ee880-d04d-11eb-9820-089df51c86fe.png">

<img width="1002" alt="121393077-465d0500-c950-11eb-94ae-f9c5718b4e5c" src="https://user-images.githubusercontent.com/66702077/122571596-2d89d900-d04d-11eb-8930-9b09af08b250.png">

**Comment by dmitryusikriseapps** [comment]
@Meelicia Hi.
Try to add `#import <React/RCTEventDispatcher.h>` to the top of this file.
You can automate this with patch-package.

**Comment by larsgroeber** [comment]
Same issue here, but @dmitryusikriseapps answer solved it for us!

**Comment by bolan9999** [comment]
There has been a major change in my life, sorry. Updated 3.0.1-rc.2
