### ISSUE TITLE
Update documentation for `dragToHideKeyboard`

### ISSUE THREAD

**Issue by denis-tsoi-mox** [bolan9999/react-native-spring-scrollview#74]
### Type: Documentation

As noted in https://github.com/bolan9999/react-native-spring-scrollview/issues/44#issuecomment-895759840

`tapToHideKeyboard` was depreciated in favour of `dragToHideKeyboard`. 
This is applicable from: `3.0.0-rc.1`.

**Comment by bolan9999** [comment]
https://bolan9999.github.io/react-native-spring-scrollview/#/zh-cn/?id=v3%e6%9b%b4%e6%96%b0%e4%ba%86%e4%bb%80%e4%b9%88%ef%bc%9f

Sorry , forgot to translate it. Done
