### ISSUE TITLE
RN0.64.2  spring-scrollview 3.0.1-rc.5 滑动点击事件过于灵敏

### ISSUE THREAD

**Issue by JonsonHI** [bolan9999/react-native-spring-scrollview#75]
RN0.64.2  
spring-scrollview 3.0.1-rc.5

列表滑动的时候  会误触点击事件,造成直接点击进入详情之类

请问是什么问题  iOS  安卓都有这个问题

**Comment by JonsonHI** [comment]
<SpringScrollView
            ref={(ref) => (this._scrollView = ref)}
            style={styles.contentContainerStyle}
            // style={{flexDirection:'row'}}
            showsVerticalScrollIndicator={false}
            onRefresh={this._onRefresh}
            onLoading={this._onLoading}

            loadingFooter={ChineseWithLastDateFooter}
            refreshHeader={ChineseWithLastDateHeader}
            >
              <View style={styles.itemWrap}>

              
            {
              array.map((item,index)=>{
               
                return (
                  <View>
                  <TouchableOpacity>   //这里的 点击事件 在上啦下拉加载的时候很容易误触
                       
                    
                  </TouchableOpacity>
                  </View>
                )
              })

            }
            </View>
          </SpringScrollView>

**Comment by vitas61** [comment]
I have the same problem
rn 0.64.2

**Comment by bolan9999** [comment]
如果iOS都有这个问题，那么就是react native官方的问题。iOS是用的原生的ScrollView。你可以换成RN官方的ScrollView试试就知道了。

**Comment by vitas61** [comment]
On android the same problem

**Comment by bolan9999** [comment]
> On android the same problem

Change to `ScrollView` in `react-native`, what about the problem on iOS and android

**Comment by 472647301** [comment]
可以参考我的更改：https://github.com/472647301/react-native-spring-scrollview/commit/5730a1d72113eaaaba75e9f282ad58b55d1bc93d

**Comment by bolan9999** [comment]
我试试

**Comment by bolan9999** [comment]
你们所说的灵敏是否是在滚动的过程中点击屏幕停止它的滑动，它会触发里面的按钮？

**Comment by vitas61** [comment]
When touched while scrolling through the list, the onPress event is fired from the child component. There is no such thing in ScrollView. Apparently you need to somehow adjust the sensitivity.

**Comment by bolan9999** [comment]
Try 3.0.2
