### ISSUE TITLE
会一直转

### ISSUE THREAD

**Issue by agu0991** [bolan9999/react-native-spring-scrollview#8]
![tim 20181030121423](https://user-images.githubusercontent.com/31955302/47695526-64611580-dc3d-11e8-96d6-7e41f59eb75f.png)
z这样他会一直转！知道Error: Out of memory

**Comment by ATShiTou** [comment]
Demo中也有这个问题 ？

**Comment by ATShiTou** [comment]
不明白你的问题，描述也不符合规范，已关闭
