### ISSUE TITLE
do you plan support horizontal scroll in the future

### ISSUE THREAD

**Issue by z98361** [bolan9999/react-native-spring-scrollview#9]
and nested scrollview, i mean: i have listview inside VerticalScrollView, ty

**Comment by sybuena** [comment]
also been look for this one. Horizontal Scroll inside inside VerticalScrollView

**Comment by ATShiTou** [comment]
No this plan recently. There is a big problem in V2: it can not work well when js thread is stuck! I want to make it native to resolve this problem, but no one help me to build Android native module.

**Comment by ATShiTou** [comment]
@z98361 @sybuena 

Now , I did, I have create a native android ScrollView, Horizontal is not supported now, but it will support it in the future.

If you are free , you can clone the V2 branch to test it by the Example!

**Comment by bolan9999** [comment]
Resolved in V2.0.2
